### ISSUE TITLE
confusing queueName logic

### ISSUE THREAD

**Issue by CodisRedding** [mateodelnorte/servicebus-register-handlers#10]
There is some really confusing code queueName logic that I'm chalking up to being a merge conflict resolution at https://github.com/mateodelnorte/servicebus-register-handlers/blob/master/index.js#L100-L108 it seems to be declaring and initializing 3 times.

``` js
  var queueName = hasQueueNameSpecified ? firstHandler.queueName :
        options.queuePrefix !== undefined ? util.format('%s-', queueName) : firstHandler.routingKey;

  var queueName = firstHandler.queueName;

  var queueName = ! isListen ?
    (firstHandler.queueName) ? firstHandler.queueName :
      (options.queuePrefix !== undefined ? util.format(options.queuePrefix + '-%s', firstHandler.routingKey) : firstHandler.routingKey) :
        firstHandler.routingKey || firstHandler.queueName;
```

**Comment by mateodelnorte** [comment]
Yup. Def looks like it. 

Can you see if #11 solves your issues?

**Comment by CodisRedding** [comment]
yup, that did it. thank you. I would have made the change and PR'd it but I wasn't sure which queueName version to use, thank you again. I'l update once you npm publish the patch.
