### ISSUE TITLE
Accessing the bus within the handlers

### ISSUE THREAD

**Issue by CodisRedding** [mateodelnorte/servicebus-register-handlers#12]
Is there a reason why we wouldn't want to access the bus that's already loaded via `bus: bus` upon registering handlers?

**Comment by mateodelnorte** [comment]
Is this a copy of #9?

**Comment by mateodelnorte** [comment]
To answer the question, no. It's commonly done, to publish events from services denoting that they've received a command, performed some work, and completed it. 

Here's a simple but complete example. Run `make run`, which will run ./bin/test-svc. You can then execute `./bin/test-listen` or `./bin/test-subscribe`. `./bin/test-listen` will send a command which will be processed by two handlers. One of them will then publish a message to `subscribe.test` which will then be handled by the two subscribe handlers. 

[sbrh-test.zip](https://github.com/mateodelnorte/servicebus-register-handlers/files/551017/sbrh-test.zip)

**Comment by CodisRedding** [comment]
yeah, that's how I am handling inter-process events and commands now. I just wanted to make sure that if I fork and expose the registered bus in the handler that I wouldn't be breaking a pattern that I wasn't seeing. 

thanks

**Comment by mateodelnorte** [comment]
You shouldn't have to expose the bus in the handler. Since `require`
effectively create singletons, you can just require your bus.js file in
which you configure your bus. See the example service zip I sent.

**Comment by CodisRedding** [comment]
yeah I get that, just thought that since that singleton is already in `this` that I could not require it.
