### ISSUE TITLE
rejected error msg not showing in error queue

### ISSUE THREAD

**Issue by CodisRedding** [mateodelnorte/servicebus-register-handlers#13]
I was assuming that an error message was going to show in the reject queue but the queued error looks like this: 

```

Exchange	(AMQP default)
Routing Key	todo.create.error
Redelivered	○
Properties	
headers:	
rejected:	4
Payload
164 bytes
Encoding: string
{"data":{"title":"work","completed":false},"datetime":"Thu, 10 Nov 2016 17:58:33 GMT","type":"todo.create","cid":"6e7caef0-ddc4-460b-8537-7317ff2feec0","handle":{}}
```

```js
handlers({
  bus: bus,
  handleError: function(msg, error) {
    const em = 'error handling %s: %s. rejecting message w/ cid %s and correlationId %s.';
    logger.error(em, msg.type, error, msg.cid, msg.correlationId);
    logger.error(error);

    msg.handle.reject(function() {
      throw error;
    });
  },
  path: './lib/handlers',
  queuePrefix: config.SERVICE_NAME
});
```

**Comment by mateodelnorte** [comment]
That's the message that caused your error. You should log errors separately. Logs + your code + data (which is the message in the queue) will tell you everything you know about your error. You can then choose to do something with the message in the error queue (like drop it, resend it to another queue, or create a script to manually update your system).

**Comment by mateodelnorte** [comment]
To phrase another way, error messages/descriptions are not queued. Poison messages (those that continually fail a process) are moved to an error queue for human inspection, and to cause the service to stop failing.
