### ISSUE TITLE
Using globbed paths

### ISSUE THREAD

**Issue by mbonig** [mateodelnorte/servicebus-register-handlers#14]
I'd like to use a glob for the path to the listeners. I was going to fork, replace this:

```
if (options.path) {
    var i = 0;
    var handlers = objectifyFolder({
      fn: function (mod, result) {
        if ( ! (mod.queueName || mod.routingKey) || ! (mod.listen || mod.subscribe)) return;
        addHandler(options.pipelines, new Handler(mod));
      },
      path: options.path
    });

```

Would that be the right place to do so? If so, I just need to make sure that for each handler that shows up in the glob is passed to addHandler as mod, correct?

I'm thinking of using something like requireDir/require-dir to get the files instead of relying on objectifyFolder.

**Comment by mateodelnorte** [comment]
The change would be in `objectify-folder`, then just update package.json here. 

If you can find a direct replacement for readdirSync that brings back a list of all files, respecting globs, you may be able to essentially replace this line: https://github.com/mateodelnorte/objectify-folder/blob/master/index.js#L23

**Comment by mateodelnorte** [comment]
Looks like you can just do a glob.sync using https://www.npmjs.com/package/glob

**Comment by mateodelnorte** [comment]
Went ahead and made the updates for you. 

➜  servicebus-register-handlers git:(master) npm publish
+ servicebus-register-handlers@0.1.7

**Comment by mbonig** [comment]
Thanks, I'll check it out. Do you have an example? Also, what's the callback in the subscribe function? What does that initiate?

**Comment by mateodelnorte** [comment]
Yup. Example in the tests: https://github.com/mateodelnorte/servicebus-register-handlers/blob/master/test/index.js#L74

servicebus-register-handlers works with servicebus-retry. as such, if your queues are `ack:true` when you execute the callback in listen or subscribe, it will acknowledge the message and pop it off rabbitmq. If you pass an error to either callback, it will use servicebus-retry's retry functionality until maxRetries is exceeded, then it will dead-letter the message to an error queue matching the routingKey + ".error"

**Comment by mbonig** [comment]
thanks for the help!

**Comment by mateodelnorte** [comment]
Sure thing. Happy to help any time. In fact, feel free to join nycnode.com/slack and ask questions on there in real time.
