### ISSUE TITLE
Cant require from within handlers

### ISSUE THREAD

**Issue by asanger** [mateodelnorte/servicebus-register-handlers#38]
Not sure why this is, but I’m unable to require any modules from my handlers using a relative path. We have to dynamically build the path like this. 

```
const eventSource = require(`${process.cwd()}/lib/src/db/eventSource`);
```

Any better workarounds for handlers loaded through this plugin?

**Comment by mateodelnorte** [comment]
That is definitely not something I've seen before. Can you make an isolated
test? Have you tried switching Node versions?

**Comment by asanger** [comment]
I just created a test repo for you to checkout. 
https://github.com/asanger/servicebus-handler-test

Just run `npm install` and `npm run start:dev`. You'll see it fail with `UnhandledPromiseRejectionWarning: Error: Cannot find module '../db/eventSource'` on the command handler.

**Comment by mateodelnorte** [comment]
Using `__dirname` should fix it. I think it has to do with your typescript usage. Here's a fixed PR: https://github.com/asanger/servicebus-handler-test/pull/1. I also moved your app.ts into your src dir and did a couple other touch ups.

**Comment by asanger** [comment]
Thanks so much!
